default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: exchange-rate-app_development

test:
  <<: *default
  database: exchange-rate-app_test

production:
  <<: *default
  database: exchange-rate-app_production
  username: exchange-rate-app
  password: <%= ENV['EXCHANGE-RATE-APP_DATABASE_PASSWORD'] %>
